### ISSUE TITLE
pulgins.js is not builded

### ISSUE THREAD

**Issue by zackexplosion** [yeoman/generator-webapp#341] opened 2015-06-20 10:27 UTC
I have run `gulp build` , but in the dist folder `scripts/plugins.js` is not showing

**Comment by silvenon** [comment] 2015-06-20 18:55
Does this happen with a fresh install or did you modify your build step? `scripts/plugins.js` is showing when I build it…

Btw, don't run `gulp build`, run `gulp` instead if you want your directories to be cleaned before building.

**Comment by silvenon** [comment] 2015-06-20 18:56
I pushed some changes, though, which fix the wrong source order. (Bootstrap was loading before jQuery.)

**Comment by cstony0917** [comment] 2015-06-21 05:41
This was my index.html and gulpfile.js

https://gist.github.com/cstony0917/9829597fa5b25c36bbd7

How can I get the latest version?

**Comment by silvenon** [comment] 2015-06-21 09:59
I just released it. See the changelog [here](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.0.1).

I now see that this is a dupe of #337 and has been merged as 4b708825cfe2e86fef7af0e2dde157cb0a6eea4e.

**Closed as completed by silvenon** 2015-06-21 09:59 UTC
