### ISSUE TITLE
Gulp Build doesn't include JS lib

### ISSUE THREAD

**Issue by tuannguyenminh2086** [yeoman/generator-webapp#654] opened 2017-04-13 04:19 UTC
Dear,

I added some third-party JS in html: for examples: magicsuggest.js . But when I run GULP BUILD, it doesnt compile in plugins.js.  

  `
    
    <script src="/bower_components/lodash/dist/lodash.min.js"></script>
    <script src="/bower_components/jquery/dist/jquery.js"></script>
    

    
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/modal.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/button.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/carousel.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js"></script>
    <script src="/bower_components/bootstrap-select/dist/js/bootstrap-select.js"></script>
    <script src="/bower_components/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js"></script>
    <script src="/bower_components/jQuery-contextMenu/dist/jquery.ui.position.min.js"></script>
    <script src="/bower_components/jQuery-contextMenu/dist/jquery.contextMenu.min.js"></script>
    <script src="/bower_components/magicsuggest/magicsuggest.js"></script>

    

    
    <script src="scripts/main.js"></script>
    `

And here is bower.json

<img width="380" alt="screen shot 2017-04-13 at 11 20 12 am" src="https://cloud.githubusercontent.com/assets/1555621/24990044/31436190-203b-11e7-9621-6c5b62c72cf1.png">

----
Is there any limit of number lib we can include? I also have a problem when I add bootstrap-datepicker.js also.

Hope to get your reply soon.

**Comment by Trost123** [comment] 2017-05-31 22:34
Does magicsuggest compile into plugins.js if you don't include all those bootstrap js?
This way we could tell if the problem is high file count or magicsuggest\datepicker lib.

**Comment by UlisesGascon** [comment] 2019-10-28 19:18
I assume that this bug was fixed in #737. If not we can re-open it again 😃

**Closed as completed by UlisesGascon** 2019-10-28 19:18 UTC
